language: php

php:
  - 5.4

#before_script:
#  - composer self-update

script:
  # @todo Re-enable. For now, we know that it works.
  #- phpunit -v -c core --testsuite Unit
  # @todo Remove process isolation when no fatal errors remain.
  #   Ensure to use committed version to account for STDERR/fatal error fix.
  - ./core/vendor/phpunit/phpunit/phpunit -v --debug -c core --process-isolation --testsuite Kernel
