language: php

php:
  - 5.4

#before_script:
#  - composer self-update
#  # @todo Enable APC(u) extension.

script:
  # @todo Re-enable. For now, we know that it works.
  #- phpunit -v -c core --testsuite Unit
  # Disable XDebug after running unit tests.
  - phpenv config-rm xdebug.ini
  - php --version
  # @todo Update to new stable once all fixes are in upstream.
  - ./core/vendor/phpunit/phpunit/phpunit -v -c core --testsuite Kernel
